### ISSUE TITLE
Describe Persona Overviews

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/project-kronos#13]
Describe personas and ways they'll use this product

**Comment by andreaOrregoH** [comment]
**Persona 1: KDNK**
_Problem/Pain points:_
-Looks at multiple calendar and event providers to filter out events for the day
-Needs mainly Carbondale-specific events
-Community/public events as a priority
-No religious events

_Needs:_
-Event aggregator to see all events in one place
-Ability to single out Carbondale events
-Ability to identify community and public events
-Ability to filter out religious events
-They need a one-liner description of each event
-They need the venue, time, and date of each event

**Comment by andreaOrregoH** [comment]
Persona 2: Carbondale Arts
_Problem/ Pain points:_
-
-
-

_Needs:_
-Event aggregator to see all events in one place
-Ability to single out Carbondale events
-Ability to identify artistic events
-They need the venue, time, and date of each event
-Shareability of events
