### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by tstirrat15** [RoaringForkTech/project-kronos#19]
[Editorconfig](https://editorconfig.org/) is a pretty nifty plugin. It exists for most editors and IDEs and synchronizes everybody's settings with regards to tabs vs spaces, the style of newline, and whether there's a newline at the end of the file among others.

The idea is that it'll make sure there aren't noisy whitespace changes in PRs, and settle the tabs vs spaces debate, at least in our little corner of the internet.

**Comment by justinlewis** [comment]
sounds good to me
