### ISSUE TITLE
Add TravisCI integration

### ISSUE THREAD

**Issue by tstirrat15** [RoaringForkTech/project-kronos#21]
We'll get this running tests and linting at the very least. Eventually it can help us deploy the app as well.

**Comment by justinlewis** [comment]
@tstirrat15 Wouldn't hurt to get buy in from the rest on the slack channel for using Travis... Unless this was already agreed and I didn't know.

**Comment by justinlewis** [comment]
I'd support it.

**Comment by tstirrat15** [comment]
Yeah, this is off the back of a conversation I had with @stevetarver. CircleCI is the one I'm familiar with, but TravisCI apparently has better licensing, especially around open source projects.
