### ISSUE TITLE
Develop initial functionality to get data from a Google Calendar

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/project-kronos#22]
You can use the [this existing class](https://github.com/RoaringForkTech/project-kronos/blob/master/src/calendar_provider.py) to build out the initial get request.

As a starting point we could use the RFT calendar: https://calendar.google.com/calendar/b/3?cid=cm9hcmluZ2Zvcmt0ZWNobm9sb2dpc3RzQGdtYWlsLmNvbQ

Other calendar options should be identified as a result of [this ticket](https://github.com/RoaringForkTech/project-kronos/issues/1).

**Comment by tstirrat15** [comment]
Hmm.

The way that the google oauth authentication flow goes requires a [web server](https://developers.google.com/identity/protocols/OAuth2WebServer) to act as the redirect target from the oauth flow.

It looks like it'll be possible to set it up locally, and that it'll work in production, but it means that having a web server chosen and set up is a prerequisite.

**Comment by tstirrat15** [comment]
Though that won't be necessary for a [first run](https://developers.google.com/calendar/quickstart/python) - you can force authentication to happen synchronously and locally. It's just going to be a temporary solution.
