### ISSUE TITLE
Add a linter to the project

### ISSUE THREAD

**Issue by tstirrat15** [RoaringForkTech/project-kronos#28]
This'll help keep code clean across the app and remove gotchas for people new to Python.

There's a few different options, though:

* [Flake8](http://flake8.pycqa.org/en/latest/)
* [Pylint](https://www.pylint.org/)
* [Black](https://github.com/psf/black)

Plus others that I'm not aware about. Thoughts? I've only used `flake8`, and while it's useful, I don't like it as much as a tool like `eslint` (the other linter that I've a good amount of experience with).

**Comment by tstirrat15** [comment]
I hear good things about Black.

**Comment by tstirrat15** [comment]
Black is a formatter, not a linter. I imagine Prettier is going to be the same.

**Comment by justinlewis** [comment]
We also need to add MyPy to utilize typing.

**Comment by tstirrat15** [comment]
I'mma make that a separate issue.
