### ISSUE TITLE
Create basic code structure

### ISSUE THREAD

**Issue by stevetarver** [RoaringForkTech/project-kronos#4]
As an IC, I need definition of basic elements and isolation of independent pieces so that my work does not overlap / conflict with other's work.

Create files and stub code to identify basic pipeline flow and orchestration.

Complete when:
* separate files defined for each stage in the event processing pipeline
* main.py orchestrates individual elements

**Comment by tstirrat15** [comment]
@stevetarver is this one done, or is there more work to do?
